name: Java CI with Maven
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    uses: ./.github/workflows/jenkins-parity.yml
    with:
      diagnostics: false
      source_ref: ${{ github.sha }}
